// File Location: src/app/admin/faq-manager/page.js
"use client";

import { useEffect, useRef, useState } from "react";

export default function AdminFaqEditorDashboardPage() {
  const editorRef = useRef(null);
  const [isReady, setIsReady] = useState(false);
  const [question, setQuestion] = useState("");
  const [isPinned, setIsPinned] = useState(false);

  useEffect(() => {
    // Client-side execution confirm karne ke liye dynamic imports loop
    if (typeof window !== "undefined") {
      import("@editorjs/editorjs").then((EditorJSModule) => {
        const EditorJS = EditorJSModule.default;
        
        // Block sub-tools load ho rahe hain
        Promise.all([
          import("@editorjs/header"),
          import("@editorjs/list"),
          import("@editorjs/image")
        ]).then(([Header, List, ImageTool]) => {
          
          if (!editorRef.current) {
            const editor = new EditorJS({
              holder: "editorjs_block_container",
              placeholder: "Yahan par apna detail answer image aur lists ke sath likhein...",
              tools: {
                header: {
                  class: Header.default,
                  inlineToolbar: true,
                },
                list: {
                  class: List.default,
                  inlineToolbar: true,
                },
                image: {
                  class: ImageTool.default,
                  config: {
                    // NestJS backend route jahan image compress hoke cloudinary pe jayegi
                    endpoints: {
                      byFile: "http://localhost:4000/api/admin/faq/upload-media", 
                    }
                  }
                }
              },
              data: {},
              onReady: () => {
                setIsReady(true);
              }
            });
            editorRef.current = editor;
          }
        });
      });
    }

    // Component unmount hone par editor ko cleanup karne ke liye
    return () => {
      if (editorRef.current && typeof editorRef.current.destroy === "function") {
        editorRef.current.destroy();
        editorRef.current = null;
      }
    };
  }, []);

  const handleSaveFaqPayload = async () => {
    if (!editorRef.current || !question) {
      alert("Please fill the question before saving!");
      return;
    }

    // EditorJS se poora structured blocks array nikalna
    const savedBlocksData = await editorRef.current.save();
    
    // Final payload jo NestJS Backend API ko hit karega
    const faqPayload = {
      question: question,
      slug: question.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)+/g, ""),
      answerJson: savedBlocksData, // Yeh text, image url, list sab database me JSON formats me save kar dega
      isPinned: isPinned
    };

    console.log("Sending clean dynamic data array to NestJS backend...", faqPayload);
    
    // Aapka temporary local check
    alert("Success! FAQ Data serialized. Check console to see JSON blocks generated by EditorJS.");
    
    // Inputs resetting
    setQuestion("");
    if (editorRef.current && typeof editorRef.current.clear === "function") {
      editorRef.current.clear();
    }
  };

  return (
    <div className="bg-slate-900 min-h-screen text-slate-200 p-4 md:p-10 font-sans antialiased">
      <div className="max-w-4xl mx-auto space-y-6">
        
        {/* Admin Dashboard Page Header */}
        <div className="border-b border-slate-800 pb-4">
          <span className="text-[10px] font-mono text-amber-400 bg-amber-950/60 border border-amber-900 px-2 py-0.5 rounded font-black tracking-widest uppercase">
            CMS Rich Editor Space
          </span>
          <h1 className="text-2xl font-black text-white tracking-tight mt-2">
            SBS Production FAQ Blueprint Studio
          </h1>
          <p className="text-xs text-slate-400 font-medium">
            Yahan se aap new dynamic FAQs rich text format me create kar sakte hain. Images direct compress hokar Cloudinary me jayengi.
          </p>
        </div>

        {/* Input Fields Content Blocks */}
        <div className="bg-slate-950 border border-slate-800 p-6 rounded-2xl space-y-5">
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-black text-slate-400 tracking-wider">
              Enter FAQ Question / Inquiry Statement
            </label>
            <input 
              type="text" 
              placeholder="e.g. Conveyor belt ki load capacity kitni hai?" 
              value={question} 
              onChange={e => setQuestion(e.target.value)} 
              className="w-full bg-slate-900 border border-slate-700 focus:border-blue-500 rounded-xl px-4 py-3 text-xs text-slate-100 font-bold focus:outline-none transition-all" 
            />
          </div>

          <div className="flex items-center gap-2 bg-slate-900/60 border border-slate-800/80 p-3 rounded-xl max-w-sm">
            <input 
              type="checkbox" 
              id="pin_faq"
              checked={isPinned} 
              onChange={e => setIsPinned(e.target.checked)} 
              className="w-4 h-4 accent-blue-500 cursor-pointer" 
            />
            <label htmlFor="pin_faq" className="text-xs font-bold text-slate-300 cursor-pointer select-none">
              Pin this FAQ directly to Contact Us view
            </label>
          </div>

          {/* EDITORJS ACTUAL INTERACTIVE SHEET CANVAS CONTAINER */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-black text-slate-400 tracking-wider block">
              Answer Body (Rich Multi-Media Blocks)
            </label>
            <div className="bg-slate-900 border border-slate-700/80 rounded-2xl p-4 min-h-[350px]">
              {/* Target div jahan editor injection setup hota hai */}
              <div 
                id="editorjs_block_container" 
                className="bg-white text-slate-900 rounded-xl p-6 min-h-[280px] text-xs font-semibold prose max-w-none"
              ></div>
            </div>
          </div>

          {/* Action Trigger Node */}
          <div className="pt-2 flex justify-end">
            <button 
              onClick={handleSaveFaqPayload}
              disabled={!isReady}
              className="bg-blue-600 disabled:bg-slate-800 disabled:text-slate-500 font-black text-xs text-white px-6 py-3.5 rounded-xl uppercase tracking-widest hover:bg-blue-500 shadow-xl transition-all"
            >
              🚀 Save & Publish FAQ ➔
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}